[package]
name = "rgba"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.3.2", features = ["derive"] }
dirs = "5.0.1"
iced = "0.13.1"
iced_aw = "0.11.0"
num_enum = "0.7.3"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
